config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  resources :reviews

  root 'reviews#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
 
    if user.role_id
      if(user.role.title == 'admin')
        can :read, ActiveAdmin::Page, :name => "Dashboard"
        can :manage, :all
      elsif (user.role.title == 'manager')   
        can :read, ActiveAdmin::Page, :name => "Dashboard"  
        can :read, Review
        can :update, Review
        can :create, Review
        cannot :delete, Review
      elsif (user.role.title == 'user')  
        can :read, ActiveAdmin::Page, :name => "Dashboard"   
        can :read, Review
        cannot :update, Review
        can :create, Review
        cannot :delete, Review
      end   
    else
      can :read, ActiveAdmin::Page, :name => "Dashboard"
      can :read, Review
      cannot :update, Review
      cannot :create, Review
      cannot :delete, Review
    end   

 

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :name, presence: true, length: { maximum:  50, minimum: 3 }
  validates :message, presence: true, length: { maximum:  500, minimum: 3 }

  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  belongs_to :role          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  load_and_authorize_resource
  

  def access_denied(exception)
    redirect_to root_path, :alert => exception.message
  end  

  #def authenticate_active_admin_user!
  #  authenticate_user!
  #  unless current_user.superadmin?
  #    flash[:alert] = "Unauthorized Access!"
  #    redirect_to root_path
  #  end
  #end    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_filter :authenticate_active_admin_user!, only: [:edit, :update, :destroy]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  #layout 'appl_test'

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      ReviewMailer.welcome_email(@review).deliver_now
      flash[:success] = 'review saved'
      redirect_to root_path
    else
      flash.now[:error] = 'review not saved'
      render 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :email, :message, :image)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource
end


class UsersController < Devise::UsersController

  after_filter :find_all_blog_posts, only: [:create]

  protected
  def find_all_blog_posts
    p '---------------------------------------'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/appl_test.html.erb
<!DOCTYPE html>

<html lang="ru">
  <head>
    <title>AdminBook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container content_container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <div class="row">
            <div class="col-xs-12">            
              <%= yield %>
            </div>
          </div>
        </div>        
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <aside>
    <% if user_signed_in? %>
        <span>Здравствуйте, <%= current_user.email %></span>
        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete, class: 'btn-default btn' %>
    <% else %>
        <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_password_path %>
    <% end %>
    <hr />
    <% if can? :read, ActiveAdmin::Page, :name => "Dashboard" %>
      0<%= link_to 'to adminpanel', admin_root_path %>
    <% end %>    
    <br>
    <% if can? :read, :all %>
      1<%= link_to 'to adminpanel', admin_root_path %>
    <% end %>  
    <br>
    <% if can? :manager, :all %>
      2<%= link_to 'to adminpanel', admin_root_path %>
      2<%= link_to 'to adminpanel', admin_root_path %>
      2<%= link_to 'to adminpanel', admin_root_path %>
    <% end %>            
    <hr />
  </aside>

  <%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cell">
    <%= label_tag(:name, "name:") %>   
    <%= f.text_field(:name, class: 'form-control') %>  
  </div>

  <div class="cell">
    <%= label_tag(:email, "email:") %> 
    <%= f.text_field(:email, class: 'form-control') %>  
  </div>

  <div class="cell">
    <%= label_tag(:message, "message:") %>
    <%= f.text_area(:message, class: 'form-control wysiwyg', id: 'wysiwyg') %>  
  </div>    

  <div class="row">
    <div class="col-xs-12 col-sm-2">
      <%= f.label :image %>
    </div>
    <div class="col-xs-12 col-sm-10">
      <%= f.file_field  :image %>
    </div>
  </div>   

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<%= link_to 'New Review', new_review_path if can? :create, Review %>

<br>

<table border="1">
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>message</th>
      <th>image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.email if review.email %></td>
        <td><%= review.message.html_safe %></td>
        <td>
        <%= image_tag(review.image.url(:thumb), alt: '') if review.image_file_name %>
        </td>
        <td><%= link_to 'Show', review if can? :read, Review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) if can? :update, Review %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Review %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= @review.name %>
<br />
<%= @review.email %>
<br />
<%= @review.message %>
<hr />

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>